version: '3'
services:
  db:
    image: mysql:latest
    ports:
      - "8050:3306"
    environment:
  - MYSQL_DATABASE=company
  - MYSQL_USER=geetanjali@localhost
  - MYSQL_PASSWORD=Geetanjali-14
    volumes:
      - ./data:/var/lib/mysql
