apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{name}}
    component: jobs
    tier: apps
    service: {{serviceTag}}
    jobType: kafka
  name: {{name}}
  namespace: {{namespace}}
spec:
  progressDeadlineSeconds: 600
  replicas: {{replicas}}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{name}}
      component: jobs
      tier: apps
      service: {{serviceTag}}
      jobType: kafka
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/lifePreStopCyclePortCheck: "{{environmentVariables.NODE_JOB_PORT}}"
        sidecar.istio.io/proxyCPU: {{proxyCPU}}
        sidecar.istio.io/proxyMemory: {{proxyMemory}}
      labels:
        app: {{name}}
        component: jobs
        tier: apps
        service: {{serviceTag}}
        jobType: kafka
      namespace: {{namespace}}
    spec:
      containers:
        - command:
            - /bin/bash
            - -ce
            - while [ $(netstat -plunt | grep tcp | grep 15020 | wc -l | xargs) -eq 0 ]; do sleep 1; done 
              && sleep 5s && cd /home/salesmate 
              && cp /home/salesmate/config-files/config.js config/service-configuration/{{environmentVariables.NODE_ENV}}.js 
              && cp /home/salesmate/service-endpoints/config.js config/service-endpoints/{{environmentVariables.NODE_ENV}}.js 
              && cp /home/salesmate/backend-config/config.js config/backend-config/{{environmentVariables.NODE_ENV}}.js 
              && cp /home/salesmate/gcp-keys/gcp-service-account-key.json config/gcp-service-account-key.json 
              && source /home/salesmate/.bash_profile
              && nvm use {{nodeVersion}} && node --max-old-space-size={{maxOldSpaceSize}} --expose-gc {{fileToRun}}
          env:
            - name: NODE_ENV
              value: {{environmentVariables.NODE_ENV}}
            - name: NODE_JOB_PORT
              value: "{{environmentVariables.NODE_JOB_PORT}}"
          image: "gcr.io/{{PROJECT_ID}}/{{IMAGE_NAME}}:{{IMAGE_TAG}}"
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/bash
                  - -c
                  - kill -TERM `pgrep node`
          name: {{name}}
          resources:
            requests:
              cpu: {{resources.request.cpu}}
              memory: {{resources.request.memory}}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: client-certs
              mountPath: /cockroach-certs
            - name: tmp
              mountPath: /home/salesmate/tmp
            - name: config-file
              mountPath: /home/salesmate/config-files
            - name: service-endpoints
              mountPath: /home/salesmate/service-endpoints
            - name: backend-configmap
              mountPath: /home/salesmate/backend-config
            - mountPath: /home/salesmate/gcp-keys
              name: gcp-keys
      dnsConfig:
        options:
          - name: ndots
            value: "1"
          - name: single-request-reopen
            value: ""
      dnsPolicy: ClusterFirst
      initContainers:
        - command:
            - /bin/ash
            - -ecx
            - /request-cert -namespace=${POD_NAMESPACE} -certs-dir=/cockroach-certs -type=client
              -user=root -symlink-ca-from=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          image: cockroachdb/cockroach-k8s-request-cert:0.4
          imagePullPolicy: IfNotPresent
          name: init-certs
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /cockroach-certs
              name: client-certs
      nodeSelector:
        pool: jobs
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: cockroachdb
      serviceAccountName: cockroachdb
      terminationGracePeriodSeconds: 120
      volumes:
        - name: client-certs
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: config-file
          configMap:
            name: {{serviceTag}}-configmap
        - name: service-endpoints
          configMap:
            name: service-endpoints-configmap
        - name: backend-configmap
          configMap:
            name: default-service-configmap
        - name: gcp-keys
          configMap:
            defaultMode: 420
            name: salesmate-gcp-keys
